name: Daily Refresh
on:
  schedule:
    - cron: '0 8 * * *'   # Every day at 8 AM UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger rebuild
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pages/builds
